version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - leny
  ignore:
  - dependency-name: open
    versions:
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.4
    - 8.0.5
    - 8.0.6
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: express-handlebars
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  registries:
  - npm-registry-npm-fontawesome-com
